title: "[General] "
labels: ["General Introduction"]
body:
  - type: textarea
    id: improvements
    attributes:
      label: Your contribution
      description: "Suggestions, ideas and opinions go here ..."
      value: 
      render: bash
    validations:
      required: true
  - type: checkboxes
    attributes:
      label: Required
      options:
        - label: I am not reporting an issue ([how to report issues](https://github.com/marcelglueck/BEpipeR?tab=readme-ov-file#faq)).
          required: true
        - label: I promise to keep the discussion civil.
          required: true
        - label: I am adhering to any potential additional points listed [here](https://github.com/marcelglueck/BEpipeR/discussions/1).
          required: true
