title: "[General] "
labels: ["General Introduction"]
body:
  - type: textarea
    id: improvements
    attributes:
      label: Your contribution
      description: "Suggestions, ideas, opinions go here ..."
      value: 
      render: bash
    validations:
      required: true
  - type: checkboxes
    attributes:
      label: Required
      options:
        - label: I am not posting any code of the pipeline.
          required: true
  - type: markdown
    attributes:
      value: |
        ### The thrilling conclusion
        _to our template_
