title: "[General] "
labels: ["General Introduction"]
body:
  - type: textarea
    id: improvements
    attributes:
      label: Your contribution
      description: "Suggestions, ideas and opinions go here ..."
      value: 
      render: bash
    validations:
      required: true
  - type: checkboxes
    attributes:
      label: Required
      options:
        - label: I am aware that posting any code of the pipeline is **NOT permitted**. I am adhering to this rule.
          required: true
        - label: I promise to keep the discussion civil.
          required: true
        - label: I am adhering to any potential additional points listed [here](https://github.com/marcelglueck/BEpipeR/discussions/1).
          required: true
