title: "[General] "
labels: ["General Introduction"]
body:
  - type: textarea
    id: improvements
    attributes:
      label: Your content
      description: "Suggestions, ideas, opinions"
      value: 
      render: bash
    validations:
      required: true
  - type: checkboxes
    attributes:
      label: Check that box!
      options:
        - label: This one!
          required: true
        - label: I won't stop you if you check this one, too
  - type: markdown
    attributes:
      value: |
        ### The thrilling conclusion
        _to our template_
