title: "[General] "
labels: ["General Introduction"]
body:
  - type: textarea
    id: improvements
    attributes:
      label: Your contribution
      description: "Suggestions, ideas, opinions go here ..."
      value: 
      render: bash
    validations:
      required: true
  - type: checkboxes
    attributes:
      label: Required
      options:
        - label: I am aware that posting any code of the pipeline is not permitted. I am adhering to this rule.
          required: true
        - label: I promise to keep the discussion civil.
          required: true
